USE PROYECTO_AlonsoMauricio;


-- -- CARGAMOS LAS TABLAS PARAMÉTRICAS

INSERT INTO envergadura (tipo_envergadura) VALUES
('Micro'),
('Pequeña'),
('Mediana'),
('Grande');

INSERT INTO estado (nombre_estado) VALUES
('Instrumentación'),
('Amortizando'),
('Cancelado'),
('Desistido'),
('Moroso');

INSERT INTO Pais (nombre_pais) VALUES
('Argentina'),
('Brasil'),
('Chile'),
('Colombia'),
('Ecuador'),
('Perú'),
('Uruguay'),
('Venezuela'),
('México'),
('Estados Unidos'),
('Canadá'),
('España'),
('Francia'),
('Alemania'),
('Italia'),
('Reino Unido'),
('Australia'),
('China'),
('Japón'),
('India'),
('Rusia'),
('Sudáfrica'),
('Nueva Zelanda'),
('Corea del Sur'),
('Indonesia'),
('Filipinas'),
('Malasia'),
('Singapur'),
('Tailandia'),
('Vietnam'),
('Bangladesh'),
('Pakistan'),
('Nigeria'),
('Egipto'),
('Kenia'),
('Ghana'),
('Marruecos'),
('Argelia'),
('Túnez'),
('Portugal'),
('Grecia'),
('Turquía'),
('Irán'),
('Arabia Saudita'),
('Emiratos Árabes Unidos'),
('Israel'),
('Qatar'),
('Kuwait'),
('Irak');
  
     
INSERT INTO provincia (nombre_provincia) VALUES
('Buenos Aires'),
('CABA'),
('Córdoba'),
('Santa Fe'),
('Mendoza'),
('Tucumán'),
('Entre Ríos'),
('Salta'),
('Chaco'),
('Corrientes'),
('Santiago del Estero'),
('San Juan'),
('Jujuy'),
('Río Negro'),
('Neuquén'),
('Formosa'),
('Chubut'),
('San Luis'),
('Catamarca'),
('La Rioja'),
('La Pampa'),
('Santa Cruz'),
('Tierra del Fuego');
    
INSERT INTO dep (nombre_dep, telefono_dep, email_dep) VALUES
('DEP - Buenos Aires','1143170954', 'caba@cfd.org.ar'),
('DEP - La Plata','2213130954', 'buenosaires@cfd.org.ar'),
('DEP - Catamarca','3833171652', 'chaco@cfd.org.ar'),
('DEP - Resistencia','3623179952', 'chaco@cfd.org.ar'),
('DEP - Rawson','2804170970', 'chubut@cfd.org.ar'),
('DEP - Córdoba','3513170920', 'cordoba@cfd.org.ar'),
('DEP - Resistencia','3623155554', 'corrientes@cfd.org.ar'),
('DEP - Paraná','3433170733', 'entrerios@cfd.org.ar'),
('DEP - Formosa','3703171984', 'formosa@cfd.org.ar'),
('DEP - San Salvador de Jujuy','3883171224', 'jujuy@cfd.org.ar'),
('DEP - Santa Rosa','2954170353', 'lapampa@cfd.org.ar'),
('DEP - La Rioja','3803112254', 'larioja@cfd.org.ar'),
('DEP - Mendoza','2613170954', 'mendoza@cfd.org.ar'),
('DEP - Posadas','3763174654', 'misiones@cfd.org.ar'),
('DEP - Neuquén','2993144554', 'neuquen@cfd.org.ar'),
('DEP - Viedma','1143172234', 'rionegro@cfd.org.ar'),
('DEP - Salta','2920115254', 'salta@cfd.org.ar'),
('DEP - San Juan','2643122254', 'sanjuan@cfd.org.ar'),
('DEP - San Luis','1143333954', 'sanluis@cfd.org.ar'),
('DEP - Río Gallegos','2663170662', 'santacruz@cfd.org.ar'),
('DEP - Santa Fe','2423174594', 'santafe@cfd.org.ar'),
('DEP - Santiago del Estero','3853170222', 'santiagodelestero@cfd.org.ar'),
('DEP - Ushuaia','2901171254', 'tierradelfuego@cfd.org.ar'),
('DEP - San Miguel de Tucumán','3813173654', 'tucuman@cfd.org.ar');

INSERT INTO sector (nombre_sector) VALUES
('Industrial'),
('Agropecuario'),
('Minería'),
('Servicios'),
('Apicultura');

INSERT INTO linea (nombre_linea) VALUES
('Crédito Productivo'),
('Acciones Sustentables'),
('Financiamiento Infraestructura'),
('Adquisición capital de trabajo');


INSERT INTO asesor (nombre_asesor, idDep) VALUES
('Martina Herrera', 1),
('Nicolás Sánchez', 1),
('Valentina Gómez', 2),
('Agustín Martínez', 2),
('Camila Rodríguez', 3),
('Facundo López', 3),
('Lucía Pérez', 4),
('Matías Fernández', 4),
('Sofía Díaz', 5),
('Santiago Ruiz', 5),
('Florencia Castro', 6),
('Lucas González', 6),
('Emma Alvarez', 7),
('Juan Pablo Rodríguez', 7),
('Renata López', 8),
('Tomás García', 8),
('Isabella Torres', 9),
('Bruno Hernández', 9),
('Catalina Martínez', 10),
('Marcos Flores', 10),
('Ana María González', 11),
('Sebastián López', 11),
('Julieta Ruiz', 12),
('Federico Díaz', 12),
('Valeria Sánchez', 13),
('Ramiro Martínez', 13),
('Antonella Pérez', 14),
('Facundo Rodríguez', 14),
('Sofía Pérez', 15),
('Ignacio Martínez', 15),
('Abril Gómez', 16),
('Joaquín Sánchez', 16),
('Mariana González', 17),
('Franco López', 17),
('Camila Rodríguez', 18),
('Gonzalo Fernández', 18),
('Josefina Gómez', 19),
('Lucas García', 19),
('Victoria Pérez', 20),
('Emilio Torres', 20),
('Florencia Martínez', 21),
('Juan Ignacio Sánchez', 21),
('Emilia Díaz', 22),
('Alejandro Ruiz', 22),
('Valentina López', 23),
('Maximiliano Fernández', 23);

INSERT INTO bancos (nombre_banco) VALUES
('Banco Provincial'),
('Banco Galicia'),
('Banco Itau'),
('Banco Nacion'),
('Banco Hipoteacario'),
('Banco BBVA'),
('Banco Macro'),
('Banco Supervielle'),
('Banco Credicoop'),
('Banco Bice'),
('Banco Santander'),
('Banco HSBC'),
('Banco Citibank'),
('Banco Patagonia'),
('Banco Hipotecario');

INSERT INTO linea (nombre_linea) VALUES
('Crédito Productivo'),
('Acciones Sustentables'),
('Financiamiento Infraestructura'),
('Adquisición capital de trabajo');